version: '3.7'

services:
  ace-nexus3:
    image: sonatype/nexus3:3.21.1
    container_name: ace-nexus3
    networks:
      ace-devops-network:
        ipv4_address: 172.20.0.7
    dns:
      - 172.18.0.2
    volumes:
    - ace-nexus3:/nexus-data
    ports:
      - 8081:8081
      - 8082:8082
    restart: always # 如果容器内应用退出了，尝试重启
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
        reservations:
          cpus: '0.10'
          memory: 128M
networks:
  ace-devops-network:
    name: ace-devops-network
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  ace-nexus3: