version: '3.7'

services:
  ace-account-base-api-web:
    image: ace-account-base-api-web:latest
    container_name: ace-account-base-api-web
    networks:
      ace-network:
        ipv4_address: ${ACE_ACCOUNT_BASE_API_WEB_IP}
    dns:
      - ${ACE_DNS_IP}
#    ports:
#      - 8848:8848
    restart: always # 如果容器内应用退出了，尝试重启

networks:
  ace-network:
    name: ${ACE_PROJECT_SUB_NETWORK_NAME}
    ipam:
      config:
        - subnet: ${ACE_PROJECT_SUB_NETWORK}