version: '3.7'

services:
  ##
  # 基础服务
  ##
  # dns 服务
  dns: # 容器名字
    image: jpillora/dnsmasq:1 #表示使用  镜像
    network_mode: host
#    networks:
#      ace-network:
#         ipv4_address: 172.18.0.2
    ports:
      - 53:53 # 将内部的 端口 映射到外部的 端口
      - 10001:8080
    volumes:
      - ${ACE_DOCKER_DNS_MASQ_CONF_FILE_PATH}:/etc/dnsmasq.conf:rw # 将同文件夹下的 data 目录 “挂载” 到内部 Ghost 数据目录
    environment:
      - HTTP_USER=${ACE_DOCKER_DNS_HTTP_USER}
      - HTTP_PASS=${ACE_DOCKER_DNS_HTTP_PASS}
    restart: always # 如果容器内应用退出了，尝试重启
    # openvpn服务
  openvpn:
    image: kylemanna/openvpn:2.4
    network_mode: host
#    networks:
#      ace-network:
#        ipv4_address: 172.18.0.10
#    dns:
#      - 172.18.104.172
    ports:
      - 1194:1194
    volumes:
      - ${ACE_DOCKER_OPEN_VPN_DIR_PATH}:/etc/openvpn:rw
    privileged: true
    restart: always # 如果容器内应用退出了，尝试重启
#    depends_on:
#      - dns
  mysql8:
    image: mysql:8.0.19
    environment:
      MYSQL_ROOT_PASSWORD: ${ACE_DOCKER_MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    restart: always # 如果容器内应用退出了，尝试重启
  ##
  # 业务服务
  ##
  ace-account-base-api-web:
    image: ace-account-base-api-web
    network_mode: host
    #    networks:
    #      ace-network:
    #        ipv4_address: 172.18.0.10
    #    dns:
    #      - 172.18.104.172
    ports:
      - 7001:7001
    privileged: true
    restart: always # 如果容器内应用退出了，尝试重启

networks:
  ace-network:
    ipam:
      config:
        - subnet: ${ACE_PROJECT_SUB_NETWORK}