version: '3.7'

services:
  ace-xxl-job:
    image: xuxueli/xxl-job-admin:2.1.2
    container_name: ace-xxl-job
    networks:
      ace-network:
        ipv4_address: ${ACE_XXL_JOB_IP}
    dns:
      - ${ACE_DNS_IP}
    environment:
      PARAMS: --spring.config.location=/application.properties
    volumes:
    - ace-xxl-job:/data/applogs
    - ${ACE_XXL_JOB_APPLICATION_PROPERTIES_PATH}:/application.properties
#    ports:
#      - 8848:8848
    restart: always # 如果容器内应用退出了，尝试重启

networks:
  ace-network:
    name: ${ACE_PROJECT_SUB_NETWORK_NAME}
    ipam:
      config:
        - subnet: ${ACE_PROJECT_SUB_NETWORK}

volumes:
  ace-xxl-job: