apiVersion: v1
kind: Service
metadata:
  name: ace-nacos-registry
  labels:
    app: ace-nacos-registry
spec:
  type: NodePort
  ports:
    - name: ace-nacos-registry
      port: 8848
      targetPort: 8848
      nodePort: 8848
  selector:
    app: ace-nacos-registry