apiVersion: v1
kind: Service
metadata:
  name: ace-account-base-api-web
  labels:
    app: ace-account-base-api-web
spec:
  type: ClusterIP
  clusterIP: 10.100.0.1
  ports:
    - port: 8080
  #      targetPort: 6379
  #      nodePort: 30379
  selector:
    app: ace-account-base-api-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ace-account-base-api-web
  labels:
    app: ace-account-base-api-web
spec:
  #securityContext:
  #privileged: true
  #serviceName: ace-account-base-api-web
  replicas: 1
  selector:
    matchLabels:
      app: ace-account-base-api-web
  template:
    metadata:
      labels:
        app: ace-account-base-api-web
          #net:
          #core:
        #somaxconn=511:
    spec:
      containers:
        - name: ace-account-base-api-web
          image: nexus3.ace.com:8082/ace-account-base-api-web:latest
          imagePullPolicy: Always
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: registry-secret
      restartPolicy: Always