version: '3.7'

services:
  ace-nexus3:
    image: sonatype/nexus3:3.21.1
    container_name: ace-nexus3
    networks:
      ace-network:
        ipv4_address: ${ACE_NEXUS3_IP}
    dns:
      - ${ACE_DNS_IP}
    volumes:
    - ace-nexus3:/nexus-data
    ports:
      - 8081:8081
    restart: always # 如果容器内应用退出了，尝试重启

networks:
  ace-network:
    ipam:
      config:
        - subnet: ${ACE_PROJECT_SUB_NETWORK}

volumes:
  ace-nexus3: