apiVersion: v1
kind: Service
metadata:
  name: ace-redis-common
  labels:
    app: ace-redis-common
spec:
  type: ClusterIP
  clusterIP: 10.100.0.2
  ports:
    - port: 6379
  #      targetPort: 6379
  #      nodePort: 30379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ace-redis-common
  labels:
    app: ace-redis-common
spec:
  #securityContext:
  #privileged: true
  serviceName: ace-redis-common
  replicas: 1
  selector:
    matchLabels:
      app: ace-redis-common
  template:
    metadata:
      labels:
        app: ace-redis-common
          #net:
          #core:
        #somaxconn=511:
    spec:
      containers:
        - name: ace-redis-common
          image: redis:rc-buster
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 450m
              memory: 4000Mi
            requests:
              cpu: 400m
              memory: 4000Mi
          env:
            - name: TZ
              value: Asia/Shanghai
          command: ["redis-server","/usr/local/etc/redis/redis.conf","--appendonly yes"]
          #          lifecycle:
          #            postStart:
          #              exec:
          #                command: ["/bin/bash", "-c", "echo 511 > /proc/sys/net/core/somaxconn; echo never > /sys/kernel/mm/transparent_hugepage/enabled;"]
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: vol-conf
              mountPath: /usr/local/etc/redis
            - name: vol-data
              mountPath: /data
      volumes:
        - name: vol-conf
          hostPath:
            path: /www/k8s/foxdev/redis/conf
            type: Directory
        - name: vol-data
          hostPath:
            path: /www/k8s/foxdev/redis/data
            type: Directory
