version: '3.7'

services:
  ace-jenkins:
    image: jenkins/jenkins:jdk11
    container_name: ace-jenkins
    networks:
      ace-network:
        ipv4_address: ${ACE_JENKINS_IP}
    dns:
      - ${ACE_DNS_IP}
    user: root
    volumes:
      - ace-jenkins:/var/jenkins_home:rw
    environment:
      JAVA_OPTS: -Xms123m -Xmx512m -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=512m -Djava.util.logging.config.file=/var/jenkins_home/log.properties
#    ports:
#      - 8080:8080
#      - 50000:50000
    restart: always # 如果容器内应用退出了，尝试重启
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.10'
          memory: 128M

networks:
  ace-network:
    name: ${ACE_PROJECT_SUB_NETWORK_NAME}
    ipam:
      config:
        - subnet: ${ACE_PROJECT_SUB_NETWORK}

volumes:
  ace-jenkins: