apiVersion: v1
kind: Service
metadata:
  name: ace-nacos-registry
  namespace: ace
  labels:
    app: ace-nacos-registry
spec:
  type: ClusterIP
  clusterIP: 10.43.1.1
  ports:
    - name: ace-nacos-registry
      port: 8848
  #      targetPort: 8848
  #      nodePort: 8848
  selector:
    app: ace-nacos-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ace-nacos-registry
  #namespace: ace-service-infrastructure
spec:
  #serviceName: ace-nacos-registry
  replicas: 1
  selector:
    matchLabels:
      app: ace-nacos-registry
  template:
    metadata:
      labels:
        app: ace-nacos-registry
    spec:
      containers:
        - name: nacos
          imagePullPolicy: IfNotPresent
          image: nacos/nacos-server:1.1.4
          resources:
            requests:
              memory: 2G
              cpu: 500m
          ports:
            - containerPort: 8848
              name: http
          env:
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: MODE
              value: "standalone"
