version: '3.7'

services:
  ace-account-cas-base-api-web:
    image: ace-account-cas-base-api-web:latest
    container_name: ace-account-cas-base-api-web
    networks:
      ace-network:
        ipv4_address: ${ACE_ACCOUNT_CAS_BASE_API_WEB_IP}
    dns:
      - ${ACE_DNS_IP}
#    ports:
#      - 8848:8848
    restart: always # 如果容器内应用退出了，尝试重启
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 512M
        reservations:
          cpus: '0.10'
          memory: 128M

networks:
  ace-network:
    ipam:
      config:
        - subnet: ${ACE_PROJECT_SUB_NETWORK}