apiVersion: v1
kind: Service
metadata:
  name: ace-rocketmq-nameserv
  labels:
    app: ace-rocketmq-nameserv
spec:
  type: ClusterIP
  clusterIP: 10.96.1.3
  ports:
    - port: 9876
  selector:
    app: ace-rocketmq-nameserv
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ace-rocketmq-nameserv
  labels:
    app: ace-rocketmq-nameserv
spec:
  serviceName: ace-rocketmq-nameserv
  replicas: 1
  selector:
    matchLabels:
      app: ace-rocketmq-nameserv
  template:
    metadata:
      labels:
        app: ace-rocketmq-nameserv
    spec:
      containers:
        - name: ace-rocketmq-nameserv
          image: foxiswho/rocketmq:4.7.0
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 450m
              memory: 2000Mi
            requests:
              cpu: 400m
              memory: 2000Mi
          env:
            - name: JAVA_OPT
              value: -Duser.home=/opt
            - name: JAVA_OPT_EXT
              value: -server -Xms2G -Xmx2G -Xmn256m
            - name: TZ
              value: Asia/Shanghai
          command: ["sh","mqnamesrv"]
          ports:
            - containerPort: 9876
          volumeMounts:
            - name: vol-logs
              mountPath: /opt/logs
            - name: vol-init-d
              mountPath: /opt/store
      volumes:
        - name: vol-logs
          hostPath:
            path: /k8s/ace-rocketmq-nameserv/logs
            type: DirectoryOrCreate
        - name: vol-init-d
          hostPath:
            path: /www/ace-rocketmq-nameserv/store
            type: DirectoryOrCreate