apiVersion: v1
kind: Service
metadata:
  name: ace-rocketmq-console
  labels:
    app: ace-rocketmq-console
spec:
  type: ClusterIP
  clusterIP: 10.96.1.5
  ports:
    - port: 8080
  selector:
    app: ace-rocketmq-console
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ace-rocketmq-console
  labels:
    app: ace-rocketmq-console

spec:
  serviceName: ace-rocketmq-console
  replicas: 1
  selector:
    matchLabels:
      app: ace-rocketmq-console
  template:
    metadata:
      labels:
        app: ace-rocketmq-console
    spec:
      containers:
        - name: ace-rocketmq-console
          image: styletang/rocketmq-console-ng:1.0.0
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 350m
              memory: 1024Mi
            requests:
              cpu: 300m
              memory: 768Mi
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: JAVA_OPTS
              value: -Drocketmq.namesrv.addr=rocketmq-namesrv.ace.com:9876 -Drocketmq.config.namesrvAddr=rocketmq-namesrv.ace.com:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false -Duser.home=/root -Xms512m -Xmx512m
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: vol-logs
              mountPath: /root/logs
      volumes:
        - name: vol-logs
          hostPath:
            path: /k8s/ace-rocketmq-console/logs
            type: DirectoryOrCreate